In [23]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd
from openpyxl import load_workbook

## 근무유형

In [24]:
work = pd.read_excel("../../data/근무 유형.xlsx", sheet_name = "Sheet1")
work

     사원번호   성명     부서 근무형태
0   54602  홍길동    제조팀   교대
1   39382  이영희    총무팀   상근
2   56925  김승우  품질관리팀   교대
3   51153  이승훈    회계팀   상근
4   66892  신성우    연구소   상근
5   73849  이철수    영업팀   상근
6   66301  김건호    제조팀   교대
7   90140  이구라    제조팀   교대
8   39814  박애라    총무팀   상근
9   60944  강인표    연구소   상근
10  90000  김경호    제조팀   교대
11  16736  한라산    영업팀   상근
12  88818  백운산    영업팀   상근
13  80185  이상민  품질관리팀   교대
14  39382  이영희    총무팀   상근
15  66301  김건호    제조팀   교대

In [25]:
w1 = work.loc[work["부서"] == "제조팀"]
w2 = work.loc[work["근무형태"].isin(["상근"])]
display(w1, w2)

     사원번호   성명   부서 근무형태
0   54602  홍길동  제조팀   교대
6   66301  김건호  제조팀   교대
7   90140  이구라  제조팀   교대
10  90000  김경호  제조팀   교대
15  66301  김건호  제조팀   교대

     사원번호   성명   부서 근무형태
1   39382  이영희  총무팀   상근
3   51153  이승훈  회계팀   상근
4   66892  신성우  연구소   상근
5   73849  이철수  영업팀   상근
8   39814  박애라  총무팀   상근
9   60944  강인표  연구소   상근
11  16736  한라산  영업팀   상근
12  88818  백운산  영업팀   상근
14  39382  이영희  총무팀   상근

In [26]:
with pd.ExcelWriter("../../data/근무 유형.xlsx", engine='openpyxl', mode='a') as writer:
    # 기존 워크북에 새로운 시트를 추가
    w1.to_excel(writer, sheet_name='제조팀', index=False)
    w2.to_excel(writer, sheet_name='상근', index=False)

In [27]:
work.loc[work["근무형태"] == "교대"]

     사원번호   성명     부서 근무형태
0   54602  홍길동    제조팀   교대
2   56925  김승우  품질관리팀   교대
6   66301  김건호    제조팀   교대
7   90140  이구라    제조팀   교대
10  90000  김경호    제조팀   교대
13  80185  이상민  품질관리팀   교대
15  66301  김건호    제조팀   교대

In [28]:
work.loc[~work["근무형태"].isin(["상근"])]

     사원번호   성명     부서 근무형태
0   54602  홍길동    제조팀   교대
2   56925  김승우  품질관리팀   교대
6   66301  김건호    제조팀   교대
7   90140  이구라    제조팀   교대
10  90000  김경호    제조팀   교대
13  80185  이상민  품질관리팀   교대
15  66301  김건호    제조팀   교대

In [29]:
## 정렬
work.sort_values(by = "사원번호")

     사원번호   성명     부서 근무형태
11  16736  한라산    영업팀   상근
1   39382  이영희    총무팀   상근
14  39382  이영희    총무팀   상근
8   39814  박애라    총무팀   상근
3   51153  이승훈    회계팀   상근
0   54602  홍길동    제조팀   교대
2   56925  김승우  품질관리팀   교대
9   60944  강인표    연구소   상근
15  66301  김건호    제조팀   교대
6   66301  김건호    제조팀   교대
4   66892  신성우    연구소   상근
5   73849  이철수    영업팀   상근
13  80185  이상민  품질관리팀   교대
12  88818  백운산    영업팀   상근
10  90000  김경호    제조팀   교대
7   90140  이구라    제조팀   교대

In [30]:
## 중복 데이터 확인
work.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15     True
dtype: bool

In [31]:
d1 = work.drop_duplicates()			# 중복 행 제거
d1

     사원번호   성명     부서 근무형태
0   54602  홍길동    제조팀   교대
1   39382  이영희    총무팀   상근
2   56925  김승우  품질관리팀   교대
3   51153  이승훈    회계팀   상근
4   66892  신성우    연구소   상근
5   73849  이철수    영업팀   상근
6   66301  김건호    제조팀   교대
7   90140  이구라    제조팀   교대
8   39814  박애라    총무팀   상근
9   60944  강인표    연구소   상근
10  90000  김경호    제조팀   교대
11  16736  한라산    영업팀   상근
12  88818  백운산    영업팀   상근
13  80185  이상민  품질관리팀   교대

In [32]:
with pd.ExcelWriter("../../data/근무 유형.xlsx", engine='openpyxl', mode='a') as writer:
    # 기존 워크북에 새로운 시트를 추가
    d1.to_excel(writer, sheet_name='중복제거', index=False)

## 식자재 주문

In [33]:
product = pd.read_excel("../../data/식자재 주문.xlsx", sheet_name = "product")
order = pd.read_excel("../../data/식자재 주문.xlsx", sheet_name = "order")
display(product, order)

    제품코드   제품명  단위    단가
0  100-1    참치   캔  2000
1  200-2    생수   개  1000
2  300-3   컵라면   개   800
3  400-3    컵밥   개  2500
4  500-1  마요네즈  그램  3000
5  600-1    케찹  그램  2500
6  700-1   식용유  리터  4000
7  800-2   음료수   병  1500
8  900-1   과자1  봉지  1500
9  950-1   과자2  봉지  2000

  대리점명   제품코드  주문수량
0   소망  200-2   200
1   소망  900-1   350
2   소망  400-3   200
3   희망  600-1   500
4   희망  800-2   150
5   자유  950-1   200
6   자유  100-1   100
7   자유  400-3    50
8   희망  200-2    80
9   희망  500-1   320

In [34]:
mapping = {"1":"청주", "2":"대구", "3":"광주"}

product["공장"] = product["제품코드"].str[-1].map(mapping)
product.head()

    제품코드   제품명  단위    단가  공장
0  100-1    참치   캔  2000  청주
1  200-2    생수   개  1000  대구
2  300-3   컵라면   개   800  광주
3  400-3    컵밥   개  2500  광주
4  500-1  마요네즈  그램  3000  청주

In [35]:
with pd.ExcelWriter("../../data/식자재 주문.xlsx", engine='openpyxl', mode='a') as writer:
    product.to_excel(writer, sheet_name='공장', index=False)

In [36]:
product = pd.read_excel("../../data/식자재 주문.xlsx", sheet_name = "product")
order = pd.read_excel("../../data/식자재 주문.xlsx", sheet_name = "order" )
display(product, order)

    제품코드   제품명  단위    단가
0  100-1    참치   캔  2000
1  200-2    생수   개  1000
2  300-3   컵라면   개   800
3  400-3    컵밥   개  2500
4  500-1  마요네즈  그램  3000
5  600-1    케찹  그램  2500
6  700-1   식용유  리터  4000
7  800-2   음료수   병  1500
8  900-1   과자1  봉지  1500
9  950-1   과자2  봉지  2000

  대리점명   제품코드  주문수량
0   소망  200-2   200
1   소망  900-1   350
2   소망  400-3   200
3   희망  600-1   500
4   희망  800-2   150
5   자유  950-1   200
6   자유  100-1   100
7   자유  400-3    50
8   희망  200-2    80
9   희망  500-1   320

In [37]:
product.set_index("제품코드", inplace = True)	# product["제품코드"]를 인덱스로 설정
order.set_index("제품코드", inplace = True)		# order["제품코드"]를 인덱스로 설정

In [38]:
display(product, order)

        제품명  단위    단가
제품코드
100-1    참치   캔  2000
200-2    생수   개  1000
300-3   컵라면   개   800
400-3    컵밥   개  2500
500-1  마요네즈  그램  3000
600-1    케찹  그램  2500
700-1   식용유  리터  4000
800-2   음료수   병  1500
900-1   과자1  봉지  1500
950-1   과자2  봉지  2000

      대리점명  주문수량
제품코드
200-2   소망   200
900-1   소망   350
400-3   소망   200
600-1   희망   500
800-2   희망   150
950-1   자유   200
100-1   자유   100
400-3   자유    50
200-2   희망    80
500-1   희망   320

In [39]:
order["제품명"] = product["제품명"]	 ## 동일한 인덱스의 product["제품명"]을 order에 추가
order["단가"] = product["단가"]	
order["주문금액"] = order["주문수량"] * order["단가"]

display(product, order)

        제품명  단위    단가
제품코드
100-1    참치   캔  2000
200-2    생수   개  1000
300-3   컵라면   개   800
400-3    컵밥   개  2500
500-1  마요네즈  그램  3000
600-1    케찹  그램  2500
700-1   식용유  리터  4000
800-2   음료수   병  1500
900-1   과자1  봉지  1500
950-1   과자2  봉지  2000

      대리점명  주문수량   제품명    단가     주문금액
제품코드
200-2   소망   200    생수  1000   200000
900-1   소망   350   과자1  1500   525000
400-3   소망   200    컵밥  2500   500000
600-1   희망   500    케찹  2500  1250000
800-2   희망   150   음료수  1500   225000
950-1   자유   200   과자2  2000   400000
100-1   자유   100    참치  2000   200000
400-3   자유    50    컵밥  2500   125000
200-2   희망    80    생수  1000    80000
500-1   희망   320  마요네즈  3000   960000

In [40]:
order.reset_index(inplace = True)
order

    제품코드 대리점명  주문수량   제품명    단가     주문금액
0  200-2   소망   200    생수  1000   200000
1  900-1   소망   350   과자1  1500   525000
2  400-3   소망   200    컵밥  2500   500000
3  600-1   희망   500    케찹  2500  1250000
4  800-2   희망   150   음료수  1500   225000
5  950-1   자유   200   과자2  2000   400000
6  100-1   자유   100    참치  2000   200000
7  400-3   자유    50    컵밥  2500   125000
8  200-2   희망    80    생수  1000    80000
9  500-1   희망   320  마요네즈  3000   960000

In [41]:
with pd.ExcelWriter("../../data/식자재 주문.xlsx", engine='openpyxl', mode='a') as writer:
    order.to_excel(writer, sheet_name='주문', index=False)