In [1]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
import folium
import datetime
import seaborn as sns
import scipy as sp
import statsmodels.formula.api as smf
import networkx as nx
import missingno as msno
import os
import sys
import urllib.request
import time
import json
import plotly.express as px
import re
import sklearn.metrics as metrics

from sklearn.decomposition import PCA
from sklearn.datasets import load_iris, load_wine, load_breast_cancer, load_diabetes
from folium.plugins import HeatMap 
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from dateutil.relativedelta import relativedelta
from sklearn.cluster import KMeans    
from yellowbrick.cluster import KElbowVisualizer
from scipy.cluster.hierarchy import dendrogram, linkage
from mpl_toolkits.mplot3d import Axes3D
from operator import itemgetter
from PIL import Image
from collections import Counter
from wordcloud import WordCloud
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import r2_score, ConfusionMatrixDisplay, confusion_matrix, accuracy_score, silhouette_score
from sklearn.neighbors import KNeighborsClassifier

# plt.rc('font', family='malgun gothic')
# plt.rcParams['axes.unicode_minus']=False  # '- 표시
plt.rc('font',family='D2CodingLigature Nerd Font')

## 1. 데이터 읽기

In [5]:
CB = pd.read_csv( '../../data/CoffeeBean.csv', encoding = 'CP949', index_col = 0, header = 0)
CB.head()

   store                              address        phone
0   차병원점            서울시 강남구 논현로 566 강남차병원1층    02-538-7615
1  강남대로점                서울시 서초구 강남대로 369 1층    02-588-5778
2  청담에스점  서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호    02-548-6052
3    신사점                   서울시 강남구 도산대로 126    02-548-2741
4    역삼점            서울시 강남구 논현로 512  지상1,2층    02-569-8051

## 2. 데이터 전처리

In [6]:
addr = []
for address in CB.address:
    addr.append(str(address).split())
    
addr

[['서울시', '강남구', '논현로', '566', '강남차병원1층'],
 ['서울시', '서초구', '강남대로', '369', '1층'],
 ['서울시', '강남구', '압구정로', '461', '네이처포엠빌딩B108,109호'],
 ['서울시', '강남구', '도산대로', '126'],
 ['서울시', '강남구', '논현로', '512', '지상1,2층'],
 ['서울시', '서초구', '강남대로', '213', '24호', '지하1층'],
 ['서울시', '강남구', '삼성로', '716', 'LEE76빌딩2층'],
 ['서울', '서초구', '반포동', '736-17', 'P빌딩', '2층'],
 ['서울시', '강남구', '언주로', '30길', '10,112', '현대비젼21', '112호'],
 ['서울시', '강남구', '선릉로', '749', '1,2층'],
 ['서울시', '강남구', '도산대로49길', '13', '1층', '17,18호'],
 ['서울시', '서초구', '강남대로', '51길', '1', '511', 'TOWER', '1층'],
 ['서울시', '강남구', '논현', '231-13호', '팍스타워지하1층'],
 ['서울', '강남구', '테헤란로87길', '46', '지하', '2층'],
 ['서울시', '강남구', '영동대로', '511', '트레이드타워', '지하1층'],
 ['서울시', '강남구', '영동대로', '607', '1,2층'],
 ['서울시', '송파구', '석촌호수로', '118', '1층'],
 ['서울시', '서초구', '서초동', '1685-8호', '101~2호,113~4호,121호'],
 ['서울시', '강남구', '논현로', '717', '1층'],
 ['서울시', '서초구', '서초대로74길', '11', '지하2층'],
 ['서울시', '서초구', '서초대로74길', '4', '삼성생명보험서초타워내지하1층'],
 ['서울특별시', '서초구', '방배중앙로', '187'],
 ['서울시', '강남구', '테헤란로', '20길', '10', '쓰리엠타워1층'],
 ['서울시', '강남구', '테헤란로', '70길', '12', '1층'],
 ['서울시', '강남구', '봉은사로', '628', '엘슨빌딩1층'],
 ['서울시', '송파구', '오금로', '11길', '7'],
 ['서울시', '강남구', '논현로', '38길', '42', '418호'],
 ['서울시', '서초구', '서초중앙로', '43', '로얄타워1층'],
 ['서울시', '강남구', '테헤란로4길', '28', '826-28호', '1층'],
 ['서울시', '강남구', '테헤란로87길', '36', '공항타워', '1층'],
 ['서울시', '강남구', '도산대로', '67길', '7,파크빌딩', '1층'],
 ['서울', '종로구', '서린동', '136', '센트리얼빌딩', '1층'],
 ['서울시', '종로구', '새문안로3길', '23', '경희궁아침상가4단지105외'],
 ['서울시', '마포구', '홍익로', '6길', '26'],
 ['서울시', '중구', '순화202', '1-94', '프레이저플레이스레지던스1층'],
 ['서울시', '종로구', '청계천로', '83', '11-4호', '지하1,지상1~3층'],
 ['서울', '중구', '남대문로7길', '16', '한컴빌딩', '1층'],
 ['서울시', '광진구', '광나루로56길', '85', '테크노마트9층35호'],
 ['서울시', '동대문구', '이문로', '106', '1~3층'],
 ['서울시', '성북구', '개운사길8', '101-3', '1층'],
 ['서울시', '중구', '칠패로', '27', '151호'],
 ['서울시', '서대문구', '창천', '18-26호', 'B1'],
 ['서울시', '광진구', '자양동', '227-342호', '롯데백화점', '옆', '더클래식500건물', '1층'],
 ['서울시', '종로구', '사직로', '130,1', '현대적선빌딩1층'],
 ['서울시', '노원구', '한글비석로', '263', '1층'],
 ['서울시', '중구', '한강대로', '416', '지하1층'],
 ['서울시', '양천구', '목동동로', '293', '현대41타워1층'],
 ['서울', '영등포구', '국제금융로', '52', '심팩빌딩', '1층'],
 ['서울시', '영등포구', '의사당대로', '97', '26-4', '교보증권빌딩1층'],
 ['서울시', '영등포구', '여의서로', '43', '한서리버파크2층'],
 ['부산광역시', '중구', '창선동', '2가', '8-2'],
 ['대전시', '서구', '문정로76', '1층'],
 ['경기도', '고양시', '일산동구', '정발산로', '24', 'I동103~203호'],
 ['경기도', '성남시', '분당구', '분당로53번길', '11', '1층2,3호'],
 ['경기도', '성남시', '분당구', '황새울로', '326', '서현빌딩상가내2층'],
 ['경기도', '성남시', '분당구', '야탑로65번길', '16,', '분당차병원', '신관동', '1층', '101호(야탑동)'],
 ['경기도', '성남시', '분당구', '황새울로', '214번길8', 'MSPlaza내1층'],
 ['경기도', '화성시', '노작로', '199', '동탄라마다호텔107호~111호'],
 ['경남', '창원시', '성산구', '중앙대로', '104', '마이우스오피스텔', '123호', '207호'],
 ['충북', '청주시', '흥덕구', '대농로', '17', '지웰시티몰', '1층', '124-1,125,126호'],
 ['서울', '중구', '세종대로', '136', '파이낸스빌딩', '지하2층'],
 ['서울시', '강남구', '테헤란로', '8길', '42', '1층'],
 ['서울시', '중구', '태평로1', '84호', 'SFC빌딩B1,1-4'],
 ['서울시', '중구', '후암로110', '581호', '서울시티타워1층'],
 ['서울시', '종로구', '대학로', '12길', '62', '지하1층,지상1,2층'],
 ['서울시', '종로구', '낙원동', '272', '오라카이스위츠', '1층'],
 ['서울시', '강남구', '테헤란로', '312', '707-2번지1층'],
 ['서울시', '관악구', '관악로', '161', '층일부', '2,3층'],
 ['서울시', '강남구', '봉은사로', '524', '코엑스', '인터컨티넨탈아케이드'],
 ['서울시', '강남구', '논현로', '167길', '9', '낙산프라자', '1층'],
 ['서울시', '구로구', '경인로', '662', '디큐브시티', '4층'],
 ['서울시', '영등포구', '국제금융로', '20', '1층'],
 ['서울시', '강남구', '선릉로93길', '6(역삼동)', '1층'],
 ['서울시', '강남구', '테헤란로1길', '29', '1층일부', '및', '2.3층'],
 ['서울시', '강남구', '삼성로', '551', '1층,2층'],
 ['서울시', '강남구', '선릉로86길', '11'],
 ['서울시', '종로구', '율곡로', '47', '1,2층'],
 ['서울시', '서초구', '강남대로', '449-3', '알고코리아빌딩', '1,2층'],
 ['서울시', '영등포구', '국제금융로10', 'IFC', 'Mall', 'L2'],
 ['서울시', '마포구', '상암산로', '82', 'SBS프리즘타워', '1층'],
 ['서울시', '금천구', '디지털로9길', '23', '마리오-2관', '패션타워3층'],
 ['경기도', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', '설계1동1F'],
 ['서울시', '서초구', '강남대로', '267', '2,3층'],
 ['서울시', '강동구', '천호대로', '1096', '1,2F'],
 ['경기도', '수원시', '팔달구', '권광로', '195', '학산빌딩1층'],
 ['경기도', '성남시', '분당구', '동판교로177번길', '25'],
 ['경기도', '고양시', '일산서구', '한류월드로', '300', '원마운트스포츠몰', '1층'],
 ['경기', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', 'C1구역식당1F'],
 ['서울시', '영등포구', '의사당대로', '97', '교보증권빌딩', '2층'],
 ['서울시', '강남구', '압구정로29길65', '지하1층'],
 ['서울시', '강남구', '테헤란로143', '고운빌딩1층'],
 ['인천광역시', '부평구', '시장로29', '1,2층'],
 ['서울시', '강남구', '강남대로442', '흥국화재빌딩', '2층'],
 ['서울시', '구로구', '디지털로300', '지밸리비즈플라자', '2층'],
 ['서울시', '서초구', '방배로178', '유중아트센터1층'],
 ['서울시', '강남구', '테헤란로87길22', '도심공항터미널', '지하1층'],
 ['서울시', '영등포구', '영중로15', '타임스퀘어', '1층'],
 ['서울시', '강남구', '봉은사로207', 'KJ타워1층'],
 ['서울시', '강남구', '테헤란로521', '파르나스몰', '지하1층'],
 ['서울시', '종로구', '새문안로5가길', '7', '1층', '일부'],
 ['경기도', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', 'PT동', '1층'],
 ['경기도',
  '김포시',
  '고촌읍',
  '아라육로',
  '152번길',
  '100',
  '현대프리미엄아울렛',
  'WEST',
  '3층',
  '618호'],
 ['서울시', '영등포구', '국제금융로8길6', '신영증권별관빌딩2층'],
 ['서울시', '용산구', '이태원로220(한남동)', '1층'],
 ['서울시', '서초구', '서초대로73길12', '세계빌딩1층'],
 ['경기도', '수원시', '영통구', '이의동', '1332', '광교아브뉴프랑', '1층', 'A122,123호'],
 ['서울시', '광진구', '아차산로563(광장동)', '대한제지빌딩', '로비층'],
 ['서울시', '송파구', '올림픽로100', '효창타워1층'],
 ['인천광역시', '중구', '공항로272', '인천국제공항탑승동3층', 'FB-C5-57'],
 ['인천광역시', '중구', '공항로272', '인천국제공항탑승동3층', 'FB-C5-68'],
 ['서울시', '송파구', '석촌호수로', '222', '제이타워', '1층'],
 ['서울시', '양천구', '오목로', '350', '목동썬텍씨티빌딩', '1층,2층'],
 ['서울시', '중구', '남대문로10길', '6', '1,2층'],
 ['경기', '이천시', '부발읍', '하이닉스반도체'],
 ['인천광역시', '연수구', '송도국제대로', '165(송도동)', '홈플러스송도점1층'],
 ['서울시', '강동구', '강동대로193', '1층'],
 ['서울시', '강남구', '영동대로85길', '9', '(대치동)', '서전빌딩1층'],
 ['경기도', '안양시', '동안구', '평촌대로', '223번길', '41(호계동', '1045-9)', '2층'],
 ['서울특별시', '강남구', '삼성로86길', '11', '거봉빌딩', '1층'],
 ['서울시', '마포구', '성암로301', 'KLID한국지역정보개발원', '1층'],
 ['경기도', '성남시', '분당구', '정자일로', '227(정자동)', '백궁지엔느주차전용빌딩', '1층'],
 ['서울특별시', '강남구', '봉은사로108', '글라스톤빌딩1층'],
 ['서울시', '강서구', '화곡6동', '1095번지', '1층'],
 ['서울시', '서대문구', '대신동', '50-5', '1층,2층(B동)'],
 ['서울시', '동대문구', '장안동', '372-1,', '1층', '일부', '및', '2층', '전체'],
 ['경기도', '수원시', '영통구', '영통로', '214번길', '8', '1층'],
 ['서울시', '서초구', '동산로', '1', '1층'],
 ['서울시', '영등포구', '문래동6가', '5번지', '1층'],
 ['부산시', '해운대구', '해운대', '해변로277', '다옴빌딩1층'],
 ['서울시', '강남구', '역삼동', '718-20', '태광타워', '1층'],
 ['경기도', '파주시', '청암로', '17번길', '17', '1층'],
 ['서울시', '서초구', '신반포로47길', '5', '건물전체', '1~3층'],
 ['서울시', '마포구', '양화로18안길', '7', '2층'],
 ['경기도', '군포시', '광정로58', '1층', '104호', '및', '2층'],
 ['강원도', '원주시', '봉화로1', 'AK플라자원주점', '1층'],
 ['경기도', '고양시', '덕양구', '화신로260번길', '26', '동민프라자', '1층', '103~107호'],
 ['서울특별시', '강남구', '테헤란로', '111', '2층'],
 ['서울특별시', '서초구', '서초대로', '397', '부띠크모나코', '1층'],
 ['서울특별시', '송파구', '송파대로', '111', '송파파크하비오', '205동', '1층', '110-113'],
 ['서울특별시', '송파구', '법원로', '114,', '엠스테이트', 'B동', '지하', '1층,', 'B145-147'],
 ['서울특별시', '중랑구', '망우로', '291', '1층'],
 ['서울특별시', '강동구', '동남로', '885', '양지빌딩', '1층'],
 ['서울시', '노원구', '노해로', '490,', '길빌딩', '2층'],
 ['서울시', '종로구', '종로', '70', '2층'],
 ['경기도', '평택시', '평남로', '862,', '로이드빌딩', '1층'],
 ['서울시', '송파구', '방이동', '44-2,', '장은빌딩', '1층'],
 ['서울특별시', '강남구', '도곡동', '543-1,', '지오빌딩', 'B1층'],
 ['서울특별시',
  '강북구',
  '한천로',
  '139길',
  '25,',
  '1층',
  '일부',
  '및',
  '2층',
  '(수유동',
  '191-70)'],
 ['인천', '연수구', '송도과학로', '16번길', '33-4', 'D동', '119호,207호'],
 ['서울특별시', '광진구', '구의강변로', '106', '삼성쉐르빌', '1층'],
 ['서울특별시', '영등포구', '국제금융로8길31', '여의도SK증권빌딩점', '1층'],
 ['서울특별시', '송파구', '충민로', '66', '가든파이브', '라이프동', '테크노관', '1층'],
 ['서울시', '송파구', '위례광장로', '230', '위례2차', '아이파크', 'B동', '1층'],
 ['서울특별시', '성북구', '삼선교로', '12', '1층'],
 ['서울특별시', '강남구', '도곡로', '408', '디마크빌딩', '1층'],
 ['서울특별시', '강남구', '강남대로112길', '20', '1층,', '2층'],
 ['경기도', '수원시', '장안구', '경수대로', '989'],
 ['서울특별시', '마포구', '양화로', '196(동교동)'],
 ['경기도', '성남시', '수정구', '수정로', '190', '(신흥동)'],
 ['서울시', '은평구', '은평로', '121(응암동),', '메디컬빌딩'],
 ['경기', '수원시', '장안구', '서부로', '2066,', '성균관대', '자연과학', '캠퍼스', 'N센터', '1층'],
 ['서울시', '영등포구', '국제금융로10', 'IFC', 'Mall', 'L2(2층)'],
 ['경기도', '화성시', '능동', '453-4,453-8,454-1', '소재', '건물(1~3층)'],
 ['경기도', '수원시', '팔달구', '인계로79', '(인계동)'],
 ['경기도', '성남시', '분당구', '야탑로64', 'DS타워', '1층'],
 ['서울시', '용산구', '한강대로95'],
 ['서울특별시', '강남구', '선릉로', '433', '세방빌딩', '1층'],
 ['경기도', '광명시', '양지로16', '아브뉴프랑', '지하', '2층', '(주)커피빈코리아', '광명아브뉴프랑점'],
 ['서울특별시', '종로구', '새문안로', '91', '고려빌딩', '1,2층'],
 ['서울특별시', '송파구', '법원로6길', '11', '환인빌딩', '1층'],
 ['서울시', '동대문구', '경희대로', '10', '(회기동)'],
 ['경기도', '파주시', '문발로', '131'],
 ['경상남도', '창원시', '성산구', '원이대로', '320,', '더시티세븐S-105호(대원동)'],
 ['서울특별시', '종로구', '종로3길', '34'],
 ['서울시', '마포구', '와우산로10길', '3,', '엘케이빌딩', '1~3층'],
 ['경기도', '안양시', '동안구', '시민대로', '260,', '1층', '104,105호'],
 ['경기도', '하남시', '미사대로', '750,', '신세계백화점', '지하1층', '식품관'],
 ['서울시', '종로구', '우정국로', '26', '센트로폴리스', '1층', 'Retail', '1-5,6'],
 ['서울특별시', '송파구', '올림픽로35길', '123', '1층'],
 ['부산', '부산진구', '서면로', '62-1', '에이스메디컬타워', '1F'],
 ['인천시', '중구', '신도시남로', '142번길', '6', '(메가스타', '영종', '139,140,141호)'],
 ['서울시', '중구', '장충동2가', '188-11,', '188-4,', '188-5'],
 ['부산', '해운대구', '센텀3로', '20', '해운대센텀호텔', '1F', '101호'],
 ['서울', '서초구', '서초중앙로', '156,', '1층'],
 ['경기도', '부천시', '부천로25'],
 ['부산', '중구', '해관로', '1', '희남빌딩', '1층'],
 ['경기도', '김포시', '태장로', '819'],
 ['서울특별시', '서초구', '반포대로70'],
 ['경기도', '남양주시', '경춘로', '1641'],
 ['서울시', '강남구', '봉은사로', '331', 'SH빌딩점', 'B1-1층'],
 ['서울시', '강서구', '강서로', '162'],
 ['경기도', '부천시', '옥길동', '768', '부천스타필드시티점', '4층'],
 ['광주광역시', '동구', '서남동', '서석로', '44', '1층', '~', '2층'],
 ['대구광역시', '중구', '동성로3길', '106'],
 ['서울', '강남구', '대치동', '943-2', '루첸타워', '1층', '로비'],
 ['경기도', '수원시', '팔달구', '덕영대로', '924', 'AK플라자', '4층'],
 ['서울시', '중구', '을지로', '35', '하나은행', '을지로본점', '24F', '내', '스마트워크센터'],
 ['서울시', '강남구', '테헤란로69길', '5', 'DT센터점', '1층'],
 ['서울시', '서초구', '강남대로', '563', '페이토플라자', '1층', '(', '잠원동', '37-1', ')'],
 ['서울시', '용산구', '장문로', '23', '몬드리안', '서울', '이태원호텔', '101호'],
 ['광주광역시', '남구', '봉선로', '168'],
 ['서울시', '노원구', '동일로', '1405,', '1층', '일부'],
 ['서울', '강남구', '광평로', '51길', '6-23', '원방테크사옥', '1층'],
 ['서울시', '송파구', '송파대로', '345', '(', '헬리오시티상가', '3블럭', 'A동', 'B1층', '22호', ')'],
 ['서울', '중구', '남대문로10길', '33', '1F'],
 ['서울시', '서초구', '서초중앙로', '209,', '해성빌딩', '1층'],
 ['경기도', '고양시', '일산동구', '정발산로', '38'],
 ['부산광역시', '북구', '학사로', '8', '(화명동', '2312),', '크리스탈타워', '2층', '201~202호'],
 ['경기도', '용인시', '처인구', '역북동', '598-7'],
 ['부산광역시', '중구', '중앙대로', '102', '팬오션빌딩', '1F'],
 ['충남', '천안시', '동남구', '만남로', '48'],
 ['제주도', '제주시', '연북로', '511'],
 ['서울시', '종로구', '대명길', '5'],
 ['경기도', '용인시', '처인구', '포곡읍', '가실리', '156-1', '(파크내', '홀랜드빌리지', '옆', '암스테르담)'],
 ['서울시', '중구', '명동', '10길', '52', '명동역', '신한은행', '사옥', '1층'],
 ['경기도', '안양시', '동안구', '엘에스로', '127', '1층'],
 ['서울', '마포구', '상암산로', '82', 'SBS', '프리즘', '타워', '1층', '로비'],
 ['서울시', '용산구', '한강대로', '23길', '55,', '아이파크몰', '테이스트파크', '7층'],
 ['경남', '진주시', '충의로', '19', 'LH진주사옥', '공감동', '1층'],
 ['서울시', '중구', '을지로', '66', '하나은행', '명동사옥', '1층'],
 ['제주도', '제주시', '애월읍', '애월해안로', '560'],
 ['서울시', '종로구', '성균관로', '25-2', '성균관대학교', '법학관', 'B2'],
 ['경기도', '화성시', '동탄중앙로220', '타임테라스A', '블록', '1층', '110호-1호'],
 ['서울특별시', '중구', '무교로', '12(무교동)', '정오빌딩', '1층'],
 ['서울시', '종로구', '종로', '98', '1층'],
 ['서울특별시', '강남구', '선릉로', '157길', '22', '2층'],
 ['서울특별시', '성북구', '고려대로', '73'],
 ['서울특별시', '중구', '세종대로', '67', '삼성', '본관빌딩', '1층', '후문', '로비', '일부']]

In [7]:
addr2 = []
for i in range(len(addr)):    
    if addr[i][0] == "서울": addr[i][0] = "서울특별시"
    elif addr[i][0] == "서울시": addr[i][0] = "서울특별시"
    elif addr[i][0] == "부산시": addr[i][0] = "부산광역시"
    elif addr[i][0] == "부산": addr[i][0] = "부산광역시"
    elif addr[i][0] == "인천": addr[i][0] = "인천광역시"
    elif addr[i][0] == "인천시": addr[i][0] = "인천광역시"
    elif addr[i][0] == "광주": addr[i][0] = "광주광역시"
    elif addr[i][0] == "대전시": addr[i][0] = "대전광역시"
    elif addr[i][0] == "울산시": addr[i][0] = "울산광역시"
    elif addr[i][0] == "세종시": addr[i][0] = "세종특별자치시"
    elif addr[i][0] == "경기": addr[i][0] = "경기도"
    elif addr[i][0] == "충북": addr[i][0] = "충청북도"
    elif addr[i][0] == "충남": addr[i][0] = "충청남도"
    elif addr[i][0] == "전북": addr[i][0] = "전라북도"
    elif addr[i][0] == "전남": addr[i][0] = "전라남도"
    elif addr[i][0] == "경북": addr[i][0] = "경상북도"
    elif addr[i][0] == "경남": addr[i][0] = "경상남도"
    elif addr[i][0] == "제주": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주도": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주시": addr[i][0] = "제주특별자치도"
    addr2.append(' '.join(addr[i]))    

addr2

['서울특별시 강남구 논현로 566 강남차병원1층',
 '서울특별시 서초구 강남대로 369 1층',
 '서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호',
 '서울특별시 강남구 도산대로 126',
 '서울특별시 강남구 논현로 512 지상1,2층',
 '서울특별시 서초구 강남대로 213 24호 지하1층',
 '서울특별시 강남구 삼성로 716 LEE76빌딩2층',
 '서울특별시 서초구 반포동 736-17 P빌딩 2층',
 '서울특별시 강남구 언주로 30길 10,112 현대비젼21 112호',
 '서울특별시 강남구 선릉로 749 1,2층',
 '서울특별시 강남구 도산대로49길 13 1층 17,18호',
 '서울특별시 서초구 강남대로 51길 1 511 TOWER 1층',
 '서울특별시 강남구 논현 231-13호 팍스타워지하1층',
 '서울특별시 강남구 테헤란로87길 46 지하 2층',
 '서울특별시 강남구 영동대로 511 트레이드타워 지하1층',
 '서울특별시 강남구 영동대로 607 1,2층',
 '서울특별시 송파구 석촌호수로 118 1층',
 '서울특별시 서초구 서초동 1685-8호 101~2호,113~4호,121호',
 '서울특별시 강남구 논현로 717 1층',
 '서울특별시 서초구 서초대로74길 11 지하2층',
 '서울특별시 서초구 서초대로74길 4 삼성생명보험서초타워내지하1층',
 '서울특별시 서초구 방배중앙로 187',
 '서울특별시 강남구 테헤란로 20길 10 쓰리엠타워1층',
 '서울특별시 강남구 테헤란로 70길 12 1층',
 '서울특별시 강남구 봉은사로 628 엘슨빌딩1층',
 '서울특별시 송파구 오금로 11길 7',
 '서울특별시 강남구 논현로 38길 42 418호',
 '서울특별시 서초구 서초중앙로 43 로얄타워1층',
 '서울특별시 강남구 테헤란로4길 28 826-28호 1층',
 '서울특별시 강남구 테헤란로87길 36 공항타워 1층',
 '서울특별시 강남구 도산대로 67길 7,파크빌딩 1층',
 '서울특별시 종로구 서린동 136 센트리얼빌딩 1층',
 '서울특별시 종로구 새문안로3길 23 경희궁아침상가4단지105외',
 '서울특별시 마포구 홍익로 6길 26',
 '서울특별시 중구 순화202 1-94 프레이저플레이스레지던스1층',
 '서울특별시 종로구 청계천로 83 11-4호 지하1,지상1~3층',
 '서울특별시 중구 남대문로7길 16 한컴빌딩 1층',
 '서울특별시 광진구 광나루로56길 85 테크노마트9층35호',
 '서울특별시 동대문구 이문로 106 1~3층',
 '서울특별시 성북구 개운사길8 101-3 1층',
 '서울특별시 중구 칠패로 27 151호',
 '서울특별시 서대문구 창천 18-26호 B1',
 '서울특별시 광진구 자양동 227-342호 롯데백화점 옆 더클래식500건물 1층',
 '서울특별시 종로구 사직로 130,1 현대적선빌딩1층',
 '서울특별시 노원구 한글비석로 263 1층',
 '서울특별시 중구 한강대로 416 지하1층',
 '서울특별시 양천구 목동동로 293 현대41타워1층',
 '서울특별시 영등포구 국제금융로 52 심팩빌딩 1층',
 '서울특별시 영등포구 의사당대로 97 26-4 교보증권빌딩1층',
 '서울특별시 영등포구 여의서로 43 한서리버파크2층',
 '부산광역시 중구 창선동 2가 8-2',
 '대전광역시 서구 문정로76 1층',
 '경기도 고양시 일산동구 정발산로 24 I동103~203호',
 '경기도 성남시 분당구 분당로53번길 11 1층2,3호',
 '경기도 성남시 분당구 황새울로 326 서현빌딩상가내2층',
 '경기도 성남시 분당구 야탑로65번길 16, 분당차병원 신관동 1층 101호(야탑동)',
 '경기도 성남시 분당구 황새울로 214번길8 MSPlaza내1층',
 '경기도 화성시 노작로 199 동탄라마다호텔107호~111호',
 '경상남도 창원시 성산구 중앙대로 104 마이우스오피스텔 123호 207호',
 '충청북도 청주시 흥덕구 대농로 17 지웰시티몰 1층 124-1,125,126호',
 '서울특별시 중구 세종대로 136 파이낸스빌딩 지하2층',
 '서울특별시 강남구 테헤란로 8길 42 1층',
 '서울특별시 중구 태평로1 84호 SFC빌딩B1,1-4',
 '서울특별시 중구 후암로110 581호 서울시티타워1층',
 '서울특별시 종로구 대학로 12길 62 지하1층,지상1,2층',
 '서울특별시 종로구 낙원동 272 오라카이스위츠 1층',
 '서울특별시 강남구 테헤란로 312 707-2번지1층',
 '서울특별시 관악구 관악로 161 층일부 2,3층',
 '서울특별시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드',
 '서울특별시 강남구 논현로 167길 9 낙산프라자 1층',
 '서울특별시 구로구 경인로 662 디큐브시티 4층',
 '서울특별시 영등포구 국제금융로 20 1층',
 '서울특별시 강남구 선릉로93길 6(역삼동) 1층',
 '서울특별시 강남구 테헤란로1길 29 1층일부 및 2.3층',
 '서울특별시 강남구 삼성로 551 1층,2층',
 '서울특별시 강남구 선릉로86길 11',
 '서울특별시 종로구 율곡로 47 1,2층',
 '서울특별시 서초구 강남대로 449-3 알고코리아빌딩 1,2층',
 '서울특별시 영등포구 국제금융로10 IFC Mall L2',
 '서울특별시 마포구 상암산로 82 SBS프리즘타워 1층',
 '서울특별시 금천구 디지털로9길 23 마리오-2관 패션타워3층',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 설계1동1F',
 '서울특별시 서초구 강남대로 267 2,3층',
 '서울특별시 강동구 천호대로 1096 1,2F',
 '경기도 수원시 팔달구 권광로 195 학산빌딩1층',
 '경기도 성남시 분당구 동판교로177번길 25',
 '경기도 고양시 일산서구 한류월드로 300 원마운트스포츠몰 1층',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 C1구역식당1F',
 '서울특별시 영등포구 의사당대로 97 교보증권빌딩 2층',
 '서울특별시 강남구 압구정로29길65 지하1층',
 '서울특별시 강남구 테헤란로143 고운빌딩1층',
 '인천광역시 부평구 시장로29 1,2층',
 '서울특별시 강남구 강남대로442 흥국화재빌딩 2층',
 '서울특별시 구로구 디지털로300 지밸리비즈플라자 2층',
 '서울특별시 서초구 방배로178 유중아트센터1층',
 '서울특별시 강남구 테헤란로87길22 도심공항터미널 지하1층',
 '서울특별시 영등포구 영중로15 타임스퀘어 1층',
 '서울특별시 강남구 봉은사로207 KJ타워1층',
 '서울특별시 강남구 테헤란로521 파르나스몰 지하1층',
 '서울특별시 종로구 새문안로5가길 7 1층 일부',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 PT동 1층',
 '경기도 김포시 고촌읍 아라육로 152번길 100 현대프리미엄아울렛 WEST 3층 618호',
 '서울특별시 영등포구 국제금융로8길6 신영증권별관빌딩2층',
 '서울특별시 용산구 이태원로220(한남동) 1층',
 '서울특별시 서초구 서초대로73길12 세계빌딩1층',
 '경기도 수원시 영통구 이의동 1332 광교아브뉴프랑 1층 A122,123호',
 '서울특별시 광진구 아차산로563(광장동) 대한제지빌딩 로비층',
 '서울특별시 송파구 올림픽로100 효창타워1층',
 '인천광역시 중구 공항로272 인천국제공항탑승동3층 FB-C5-57',
 '인천광역시 중구 공항로272 인천국제공항탑승동3층 FB-C5-68',
 '서울특별시 송파구 석촌호수로 222 제이타워 1층',
 '서울특별시 양천구 오목로 350 목동썬텍씨티빌딩 1층,2층',
 '서울특별시 중구 남대문로10길 6 1,2층',
 '경기도 이천시 부발읍 하이닉스반도체',
 '인천광역시 연수구 송도국제대로 165(송도동) 홈플러스송도점1층',
 '서울특별시 강동구 강동대로193 1층',
 '서울특별시 강남구 영동대로85길 9 (대치동) 서전빌딩1층',
 '경기도 안양시 동안구 평촌대로 223번길 41(호계동 1045-9) 2층',
 '서울특별시 강남구 삼성로86길 11 거봉빌딩 1층',
 '서울특별시 마포구 성암로301 KLID한국지역정보개발원 1층',
 '경기도 성남시 분당구 정자일로 227(정자동) 백궁지엔느주차전용빌딩 1층',
 '서울특별시 강남구 봉은사로108 글라스톤빌딩1층',
 '서울특별시 강서구 화곡6동 1095번지 1층',
 '서울특별시 서대문구 대신동 50-5 1층,2층(B동)',
 '서울특별시 동대문구 장안동 372-1, 1층 일부 및 2층 전체',
 '경기도 수원시 영통구 영통로 214번길 8 1층',
 '서울특별시 서초구 동산로 1 1층',
 '서울특별시 영등포구 문래동6가 5번지 1층',
 '부산광역시 해운대구 해운대 해변로277 다옴빌딩1층',
 '서울특별시 강남구 역삼동 718-20 태광타워 1층',
 '경기도 파주시 청암로 17번길 17 1층',
 '서울특별시 서초구 신반포로47길 5 건물전체 1~3층',
 '서울특별시 마포구 양화로18안길 7 2층',
 '경기도 군포시 광정로58 1층 104호 및 2층',
 '강원도 원주시 봉화로1 AK플라자원주점 1층',
 '경기도 고양시 덕양구 화신로260번길 26 동민프라자 1층 103~107호',
 '서울특별시 강남구 테헤란로 111 2층',
 '서울특별시 서초구 서초대로 397 부띠크모나코 1층',
 '서울특별시 송파구 송파대로 111 송파파크하비오 205동 1층 110-113',
 '서울특별시 송파구 법원로 114, 엠스테이트 B동 지하 1층, B145-147',
 '서울특별시 중랑구 망우로 291 1층',
 '서울특별시 강동구 동남로 885 양지빌딩 1층',
 '서울특별시 노원구 노해로 490, 길빌딩 2층',
 '서울특별시 종로구 종로 70 2층',
 '경기도 평택시 평남로 862, 로이드빌딩 1층',
 '서울특별시 송파구 방이동 44-2, 장은빌딩 1층',
 '서울특별시 강남구 도곡동 543-1, 지오빌딩 B1층',
 '서울특별시 강북구 한천로 139길 25, 1층 일부 및 2층 (수유동 191-70)',
 '인천광역시 연수구 송도과학로 16번길 33-4 D동 119호,207호',
 '서울특별시 광진구 구의강변로 106 삼성쉐르빌 1층',
 '서울특별시 영등포구 국제금융로8길31 여의도SK증권빌딩점 1층',
 '서울특별시 송파구 충민로 66 가든파이브 라이프동 테크노관 1층',
 '서울특별시 송파구 위례광장로 230 위례2차 아이파크 B동 1층',
 '서울특별시 성북구 삼선교로 12 1층',
 '서울특별시 강남구 도곡로 408 디마크빌딩 1층',
 '서울특별시 강남구 강남대로112길 20 1층, 2층',
 '경기도 수원시 장안구 경수대로 989',
 '서울특별시 마포구 양화로 196(동교동)',
 '경기도 성남시 수정구 수정로 190 (신흥동)',
 '서울특별시 은평구 은평로 121(응암동), 메디컬빌딩',
 '경기도 수원시 장안구 서부로 2066, 성균관대 자연과학 캠퍼스 N센터 1층',
 '서울특별시 영등포구 국제금융로10 IFC Mall L2(2층)',
 '경기도 화성시 능동 453-4,453-8,454-1 소재 건물(1~3층)',
 '경기도 수원시 팔달구 인계로79 (인계동)',
 '경기도 성남시 분당구 야탑로64 DS타워 1층',
 '서울특별시 용산구 한강대로95',
 '서울특별시 강남구 선릉로 433 세방빌딩 1층',
 '경기도 광명시 양지로16 아브뉴프랑 지하 2층 (주)커피빈코리아 광명아브뉴프랑점',
 '서울특별시 종로구 새문안로 91 고려빌딩 1,2층',
 '서울특별시 송파구 법원로6길 11 환인빌딩 1층',
 '서울특별시 동대문구 경희대로 10 (회기동)',
 '경기도 파주시 문발로 131',
 '경상남도 창원시 성산구 원이대로 320, 더시티세븐S-105호(대원동)',
 '서울특별시 종로구 종로3길 34',
 '서울특별시 마포구 와우산로10길 3, 엘케이빌딩 1~3층',
 '경기도 안양시 동안구 시민대로 260, 1층 104,105호',
 '경기도 하남시 미사대로 750, 신세계백화점 지하1층 식품관',
 '서울특별시 종로구 우정국로 26 센트로폴리스 1층 Retail 1-5,6',
 '서울특별시 송파구 올림픽로35길 123 1층',
 '부산광역시 부산진구 서면로 62-1 에이스메디컬타워 1F',
 '인천광역시 중구 신도시남로 142번길 6 (메가스타 영종 139,140,141호)',
 '서울특별시 중구 장충동2가 188-11, 188-4, 188-5',
 '부산광역시 해운대구 센텀3로 20 해운대센텀호텔 1F 101호',
 '서울특별시 서초구 서초중앙로 156, 1층',
 '경기도 부천시 부천로25',
 '부산광역시 중구 해관로 1 희남빌딩 1층',
 '경기도 김포시 태장로 819',
 '서울특별시 서초구 반포대로70',
 '경기도 남양주시 경춘로 1641',
 '서울특별시 강남구 봉은사로 331 SH빌딩점 B1-1층',
 '서울특별시 강서구 강서로 162',
 '경기도 부천시 옥길동 768 부천스타필드시티점 4층',
 '광주광역시 동구 서남동 서석로 44 1층 ~ 2층',
 '대구광역시 중구 동성로3길 106',
 '서울특별시 강남구 대치동 943-2 루첸타워 1층 로비',
 '경기도 수원시 팔달구 덕영대로 924 AK플라자 4층',
 '서울특별시 중구 을지로 35 하나은행 을지로본점 24F 내 스마트워크센터',
 '서울특별시 강남구 테헤란로69길 5 DT센터점 1층',
 '서울특별시 서초구 강남대로 563 페이토플라자 1층 ( 잠원동 37-1 )',
 '서울특별시 용산구 장문로 23 몬드리안 서울 이태원호텔 101호',
 '광주광역시 남구 봉선로 168',
 '서울특별시 노원구 동일로 1405, 1층 일부',
 '서울특별시 강남구 광평로 51길 6-23 원방테크사옥 1층',
 '서울특별시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 )',
 '서울특별시 중구 남대문로10길 33 1F',
 '서울특별시 서초구 서초중앙로 209, 해성빌딩 1층',
 '경기도 고양시 일산동구 정발산로 38',
 '부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호',
 '경기도 용인시 처인구 역북동 598-7',
 '부산광역시 중구 중앙대로 102 팬오션빌딩 1F',
 '충청남도 천안시 동남구 만남로 48',
 '제주특별자치도 제주시 연북로 511',
 '서울특별시 종로구 대명길 5',
 '경기도 용인시 처인구 포곡읍 가실리 156-1 (파크내 홀랜드빌리지 옆 암스테르담)',
 '서울특별시 중구 명동 10길 52 명동역 신한은행 사옥 1층',
 '경기도 안양시 동안구 엘에스로 127 1층',
 '서울특별시 마포구 상암산로 82 SBS 프리즘 타워 1층 로비',
 '서울특별시 용산구 한강대로 23길 55, 아이파크몰 테이스트파크 7층',
 '경상남도 진주시 충의로 19 LH진주사옥 공감동 1층',
 '서울특별시 중구 을지로 66 하나은행 명동사옥 1층',
 '제주특별자치도 제주시 애월읍 애월해안로 560',
 '서울특별시 종로구 성균관로 25-2 성균관대학교 법학관 B2',
 '경기도 화성시 동탄중앙로220 타임테라스A 블록 1층 110호-1호',
 '서울특별시 중구 무교로 12(무교동) 정오빌딩 1층',
 '서울특별시 종로구 종로 98 1층',
 '서울특별시 강남구 선릉로 157길 22 2층',
 '서울특별시 성북구 고려대로 73',
 '서울특별시 중구 세종대로 67 삼성 본관빌딩 1층 후문 로비 일부']

In [8]:
addr2 = pd.DataFrame(addr2, columns = ['address2'])
addr2.head(3)

                              address2
0            서울특별시 강남구 논현로 566 강남차병원1층
1                서울특별시 서초구 강남대로 369 1층
2  서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호

In [9]:
CB2 = pd.concat([CB, addr2], axis = 1 )
CB2.head()

,store,address,phone,address2
0,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층
1,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층
2,청담에스점,"서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호",02-548-6052,"서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호"
3,신사점,서울시 강남구 도산대로 126,02-548-2741,서울특별시 강남구 도산대로 126
4,역삼점,"서울시 강남구 논현로 512 지상1,2층",02-569-8051,"서울특별시 강남구 논현로 512 지상1,2층"

* folium은 파이썬으로 ‘인터랙티브 지도’를 만드는 라이브러리임.
* 웹 지도(줌, 클릭, 마커)를 파이썬 코드로 만들 수 있음.
* 마커 색(color): red, blue, green, purple, orange, darkred, cadetblue, black, gray
* 마커 모양(icon): info-sign(기본값), star, home, coffee, shopping-cart, user, ok, remove, flag, map-marker
* 목록에 없는거 사용시 color는 blue, icon은 info-sign 표기

In [10]:
map_osm = folium.Map(location = [37.559978, 126.975291], zoom_start = 16)

folium.Marker(
    location=[37.559978, 126.975291],
    tooltip='중심 위치',
    icon=folium.Icon(color='red', icon='star')
).add_to(map_osm)

map_osm.save('../../data/map.html')

## 3. 지오서비스웹에서 위도, 경도값 알아내기

In [ ]:
# 정제된 파일 저장

CB2.to_csv("../../data/CoffeeBean_2.csv", encoding='CP949', index=False)

### 변환 데이터가 다운로드 되었다고 가정
* ### https://www.vworld.kr/dev/v3dv_geocoderguide2_s001.do 를 이용하면 된다

In [14]:
CB_geoData = pd.read_csv('../../data/CB_geoResult.csv', encoding = 'utf8', engine = 'python')
CB_geoData.head(2)

,store,address,phone,address2,_GC_TYPE,_CLEANADDR,_X,_Y
0,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층,정,서울특별시 강남구 논현로 566 (역삼동),127.034738,37.50704
1,역삼점,"서울시 강남구 논현로 512 지상1,2층",02-569-8051,"서울특별시 강남구 논현로 512 지상1,2층",정,서울특별시 강남구 논현로 512 (역삼동),127.036521,37.50235

In [20]:
# 1. 지도 객체를 먼저 생성해야 합니다 (서울 시청 기준 예시)
map_CB = folium.Map(location=[37.5665, 126.9780], zoom_start=12)

for i, store in CB_geoData.iterrows():
    folium.Marker( location = [store['_Y'], store['_X']], tooltip = store['store'], 
                  icon = folium.Icon(color = 'red', icon = 'star')).add_to(map_CB)
                  # icon = folium.Icon()).add_to(map_CB) #default test
map_CB.save('../../data/map_CB.html')