!pip install openpyxl

In [12]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd
from openpyxl import load_workbook

In [2]:
info = pd.read_excel("../../data/직원 정보.xlsx", sheet_name = "Sheet1")
info

,순번,성,이름,영문명,사원번호,주소,전화번호
0,1,김,철수,kim cheolsu,2005-1478345,강서구 공항로 20455,010-1000-8735
1,2,박,종수,park jongsu,2010-1345972,강서구 대저중앙로 3009,010-1000-8736
2,3,김,하나,kim hana,2012-1487234,강서구 하덕로 1002,010-1000-8737
3,4,이,백만,lee baekman,2001-3747234,기장군 기장읍 연화100길,010-1000-8738
4,5,백,오십,baek osip,2002-4972944,기장군 기장읍 차성로,010-1000-8739
5,6,영웅,재준,youngwoong jaejun,2011-2382747,기장군 기장읍 기장해안로,010-1000-8740
6,7,현,빈,hyun bin,2000-2395634,남구 지게골로 10-2,010-1000-8741
7,8,장,하나,jang hana,2015-1626816,동래구 온천장로107-100,010-1000-8742
8,9,유,두울,yoo dooul,2016-4323930,동래구 동래로116,010-1000-8743
9,10,채,일,chae il,2012-3967845,북구 효열로 2502,010-1000-8744

## 텍스트 함수

In [3]:
info["성명"] = info["성"] + info["이름"]   
info["성명1"] = info[["성", "이름"]].sum(axis=1)
info

,순번,성,이름,영문명,사원번호,주소,전화번호,성명,성명1
0,1,김,철수,kim cheolsu,2005-1478345,강서구 공항로 20455,010-1000-8735,김철수,김철수
1,2,박,종수,park jongsu,2010-1345972,강서구 대저중앙로 3009,010-1000-8736,박종수,박종수
2,3,김,하나,kim hana,2012-1487234,강서구 하덕로 1002,010-1000-8737,김하나,김하나
3,4,이,백만,lee baekman,2001-3747234,기장군 기장읍 연화100길,010-1000-8738,이백만,이백만
4,5,백,오십,baek osip,2002-4972944,기장군 기장읍 차성로,010-1000-8739,백오십,백오십
5,6,영웅,재준,youngwoong jaejun,2011-2382747,기장군 기장읍 기장해안로,010-1000-8740,영웅재준,영웅재준
6,7,현,빈,hyun bin,2000-2395634,남구 지게골로 10-2,010-1000-8741,현빈,현빈
7,8,장,하나,jang hana,2015-1626816,동래구 온천장로107-100,010-1000-8742,장하나,장하나
8,9,유,두울,yoo dooul,2016-4323930,동래구 동래로116,010-1000-8743,유두울,유두울
9,10,채,일,chae il,2012-3967845,북구 효열로 2502,010-1000-8744,채일,채일

In [ ]:
info["사원번호 앞 4자리"] = info["사원번호"].str[0:4]
info["전화번호 뒤 4자리"] = info["전화번호"].str[9:13] # 전화번호 뒤에서 4자리 추출
# info["전화번호 뒤 4자리"] = info["전화번호"].str[-4:]
info

,순번,성,이름,영문명,사원번호,주소,전화번호,성명,성명1,사원번호 앞 4자리,전화번호 뒤 4자리
0,1,김,철수,kim cheolsu,2005-1478345,강서구 공항로 20455,010-1000-8735,김철수,김철수,2005,8735
1,2,박,종수,park jongsu,2010-1345972,강서구 대저중앙로 3009,010-1000-8736,박종수,박종수,2010,8736
2,3,김,하나,kim hana,2012-1487234,강서구 하덕로 1002,010-1000-8737,김하나,김하나,2012,8737
3,4,이,백만,lee baekman,2001-3747234,기장군 기장읍 연화100길,010-1000-8738,이백만,이백만,2001,8738
4,5,백,오십,baek osip,2002-4972944,기장군 기장읍 차성로,010-1000-8739,백오십,백오십,2002,8739
5,6,영웅,재준,youngwoong jaejun,2011-2382747,기장군 기장읍 기장해안로,010-1000-8740,영웅재준,영웅재준,2011,8740
6,7,현,빈,hyun bin,2000-2395634,남구 지게골로 10-2,010-1000-8741,현빈,현빈,2000,8741
7,8,장,하나,jang hana,2015-1626816,동래구 온천장로107-100,010-1000-8742,장하나,장하나,2015,8742
8,9,유,두울,yoo dooul,2016-4323930,동래구 동래로116,010-1000-8743,유두울,유두울,2016,8743
9,10,채,일,chae il,2012-3967845,북구 효열로 2502,010-1000-8744,채일,채일,2012,8744

In [5]:
info["구"] = info["주소"].str.split(" ").str[1]
info[["성", "이름", "전화번호", "구"]]

    성  이름           전화번호    구
0   김  철수  010-1000-8735  강서구
1   박  종수  010-1000-8736  강서구
2   김  하나  010-1000-8737  강서구
3   이  백만  010-1000-8738  기장군
4   백  오십  010-1000-8739  기장군
5  영웅  재준  010-1000-8740  기장군
6   현   빈  010-1000-8741   남구
7   장  하나  010-1000-8742  동래구
8   유  두울  010-1000-8743  동래구
9   채   일  010-1000-8744   북구

In [6]:
info["대문자"] = info["영문명"].str.upper()      # [영문명] 열을 대문자로 변환
info["첫 글자"] = info["영문명"].str.capitalize()   # [영문명] 열의 첫 글자만 대문자로 변환
info["단어 첫 글자"] = info["영문명"].str.title()    # 단어 첫글자만 대문자로
info[["순번", "성", "이름", "영문명", "전화번호", "대문자", "첫 글자","단어 첫 글자"]]

,순번,성,이름,영문명,전화번호,대문자,첫 글자,단어 첫 글자
0,1,김,철수,kim cheolsu,010-1000-8735,KIM CHEOLSU,Kim cheolsu,Kim Cheolsu
1,2,박,종수,park jongsu,010-1000-8736,PARK JONGSU,Park jongsu,Park Jongsu
2,3,김,하나,kim hana,010-1000-8737,KIM HANA,Kim hana,Kim Hana
3,4,이,백만,lee baekman,010-1000-8738,LEE BAEKMAN,Lee baekman,Lee Baekman
4,5,백,오십,baek osip,010-1000-8739,BAEK OSIP,Baek osip,Baek Osip
5,6,영웅,재준,youngwoong jaejun,010-1000-8740,YOUNGWOONG JAEJUN,Youngwoong jaejun,Youngwoong Jaejun
6,7,현,빈,hyun bin,010-1000-8741,HYUN BIN,Hyun bin,Hyun Bin
7,8,장,하나,jang hana,010-1000-8742,JANG HANA,Jang hana,Jang Hana
8,9,유,두울,yoo dooul,010-1000-8743,YOO DOOUL,Yoo dooul,Yoo Dooul
9,10,채,일,chae il,010-1000-8744,CHAE IL,Chae il,Chae Il

In [7]:
str.swapcase("ABcde")

'abCDE'

In [8]:
info["phone"] = info["전화번호"].str.replace("-", "", 1)    # 첫 번째 하이픈(-) 제거 
info["phone1"] = info["전화번호"].str.replace("-"," ")      # 모든 하이픈 (-)을 공백으로 대체
info[["순번", "성", "이름", "전화번호", "phone", "phone1"]]

   순번   성  이름           전화번호         phone         phone1
0   1   김  철수  010-1000-8735  0101000-8735  010 1000 8735
1   2   박  종수  010-1000-8736  0101000-8736  010 1000 8736
2   3   김  하나  010-1000-8737  0101000-8737  010 1000 8737
3   4   이  백만  010-1000-8738  0101000-8738  010 1000 8738
4   5   백  오십  010-1000-8739  0101000-8739  010 1000 8739
5   6  영웅  재준  010-1000-8740  0101000-8740  010 1000 8740
6   7   현   빈  010-1000-8741  0101000-8741  010 1000 8741
7   8   장  하나  010-1000-8742  0101000-8742  010 1000 8742
8   9   유  두울  010-1000-8743  0101000-8743  010 1000 8743
9  10   채   일  010-1000-8744  0101000-8744  010 1000 8744

In [9]:
# 문자열 길이
info["주소 길이"] = info["주소"].str.len()   
info[["순번", "성", "이름", "주소", "주소 길이" ]]

   순번   성  이름                주소  주소 길이
0   1   김  철수     강서구 공항로 20455     14
1   2   박  종수    강서구 대저중앙로 3009     15
2   3   김  하나      강서구 하덕로 1002     13
3   4   이  백만    기장군 기장읍 연화100길     15
4   5   백  오십       기장군 기장읍 차성로     12
5   6  영웅  재준     기장군 기장읍 기장해안로     14
6   7   현   빈      남구 지게골로 10-2     13
7   8   장  하나   동래구 온천장로107-100     16
8   9   유  두울        동래구 동래로116     11
9  10   채   일       북구 효열로 2502     12

In [10]:
info["앞뒤 공백 제거"] = info["주소"].str.strip()   
info["공백 제거 후 길이"] = info["앞뒤 공백 제거"].str.len()   # 공백 제거 문자열의 길이 구하기
info[["순번", "주소", "주소 길이", "앞뒤 공백 제거", "공백 제거 후 길이"]]

   순번                주소  주소 길이         앞뒤 공백 제거  공백 제거 후 길이
0   1     강서구 공항로 20455     14    강서구 공항로 20455          13
1   2    강서구 대저중앙로 3009     15   강서구 대저중앙로 3009          14
2   3      강서구 하덕로 1002     13     강서구 하덕로 1002          12
3   4    기장군 기장읍 연화100길     15   기장군 기장읍 연화100길          14
4   5       기장군 기장읍 차성로     12      기장군 기장읍 차성로          11
5   6     기장군 기장읍 기장해안로     14    기장군 기장읍 기장해안로          13
6   7      남구 지게골로 10-2     13     남구 지게골로 10-2          12
7   8   동래구 온천장로107-100     16  동래구 온천장로107-100          15
8   9        동래구 동래로116     11       동래구 동래로116          10
9  10       북구 효열로 2502     12      북구 효열로 2502          11

In [11]:
info.head()

,순번,성,이름,영문명,사원번호,주소,전화번호,성명,성명1,사원번호 앞 4자리,전화번호 뒤 4자리,구,대문자,첫 글자,단어 첫 글자,phone,phone1,주소 길이,앞뒤 공백 제거,공백 제거 후 길이
0,1,김,철수,kim cheolsu,2005-1478345,강서구 공항로 20455,010-1000-8735,김철수,김철수,2005,8735,강서구,KIM CHEOLSU,Kim cheolsu,Kim Cheolsu,0101000-8735,010 1000 8735,14,강서구 공항로 20455,13
1,2,박,종수,park jongsu,2010-1345972,강서구 대저중앙로 3009,010-1000-8736,박종수,박종수,2010,8736,강서구,PARK JONGSU,Park jongsu,Park Jongsu,0101000-8736,010 1000 8736,15,강서구 대저중앙로 3009,14
2,3,김,하나,kim hana,2012-1487234,강서구 하덕로 1002,010-1000-8737,김하나,김하나,2012,8737,강서구,KIM HANA,Kim hana,Kim Hana,0101000-8737,010 1000 8737,13,강서구 하덕로 1002,12
3,4,이,백만,lee baekman,2001-3747234,기장군 기장읍 연화100길,010-1000-8738,이백만,이백만,2001,8738,기장군,LEE BAEKMAN,Lee baekman,Lee Baekman,0101000-8738,010 1000 8738,15,기장군 기장읍 연화100길,14
4,5,백,오십,baek osip,2002-4972944,기장군 기장읍 차성로,010-1000-8739,백오십,백오십,2002,8739,기장군,BAEK OSIP,Baek osip,Baek Osip,0101000-8739,010 1000 8739,12,기장군 기장읍 차성로,11

In [13]:
# 새로운 시트로 추가
with pd.ExcelWriter("../../data/직원 정보.xlsx", engine='openpyxl', mode='a') as writer:
    info.to_excel(writer, sheet_name="문자열함수", index=False)

## 수학 및 통계 함수

In [14]:
score = pd.read_excel("../../data/성적 처리.xlsx", sheet_name = "Sheet1")
score

     반   성명  국어  영어  수학  사회  과학
0   1반  홍길동  93  80  94  73  64
1   2반  백일홍  93  63  76  84  92
2   3반  이삼상  94  74  86  90  70
3   1반  정말로  83  55  64  90  65
4   2반  한번도  87  95  66  75  60
5   3반  이철수  53  81  59  88  69
6   1반  김영자  71  71  51  84  57
7   2반  다니엘  87  54  95  71  97
8   3반  이미로  59  54  75  90  82
9   1반  신성삼  64  66  59  91  86
10  2반  케로로  56  76  52  64  65
11  3반  장발장  85  51  64  80  68

In [15]:
score["sum"] = score.iloc[:, 2:7].sum(axis=1)
score

     반   성명  국어  영어  수학  사회  과학  sum
0   1반  홍길동  93  80  94  73  64  404
1   2반  백일홍  93  63  76  84  92  408
2   3반  이삼상  94  74  86  90  70  414
3   1반  정말로  83  55  64  90  65  357
4   2반  한번도  87  95  66  75  60  383
5   3반  이철수  53  81  59  88  69  350
6   1반  김영자  71  71  51  84  57  334
7   2반  다니엘  87  54  95  71  97  404
8   3반  이미로  59  54  75  90  82  360
9   1반  신성삼  64  66  59  91  86  366
10  2반  케로로  56  76  52  64  65  313
11  3반  장발장  85  51  64  80  68  348

In [16]:
score["mean"] = score.iloc[:, 2:7].mean(axis=1)
score

     반   성명  국어  영어  수학  사회  과학  sum  mean
0   1반  홍길동  93  80  94  73  64  404  80.8
1   2반  백일홍  93  63  76  84  92  408  81.6
2   3반  이삼상  94  74  86  90  70  414  82.8
3   1반  정말로  83  55  64  90  65  357  71.4
4   2반  한번도  87  95  66  75  60  383  76.6
5   3반  이철수  53  81  59  88  69  350  70.0
6   1반  김영자  71  71  51  84  57  334  66.8
7   2반  다니엘  87  54  95  71  97  404  80.8
8   3반  이미로  59  54  75  90  82  360  72.0
9   1반  신성삼  64  66  59  91  86  366  73.2
10  2반  케로로  56  76  52  64  65  313  62.6
11  3반  장발장  85  51  64  80  68  348  69.6

In [17]:
score1 = score[["반","국어","영어","수학","사회","과학"]].groupby("반").sum()
score1

     국어   영어   수학   사회   과학
반
1반  311  272  268  338  272
2반  323  288  289  294  314
3반  291  260  284  348  289

In [18]:
score2 = score[["반","국어","영어","수학","사회","과학"]].groupby("반").mean()
score2

       국어    영어     수학    사회     과학
반
1반  77.75  68.0  67.00  84.5  68.00
2반  80.75  72.0  72.25  73.5  78.50
3반  72.75  65.0  71.00  87.0  72.25

In [19]:
score["순위"] = score["mean"].rank(ascending = False).astype(int)
score

     반   성명  국어  영어  수학  사회  과학  sum  mean  순위
0   1반  홍길동  93  80  94  73  64  404  80.8   3
1   2반  백일홍  93  63  76  84  92  408  81.6   2
2   3반  이삼상  94  74  86  90  70  414  82.8   1
3   1반  정말로  83  55  64  90  65  357  71.4   8
4   2반  한번도  87  95  66  75  60  383  76.6   5
5   3반  이철수  53  81  59  88  69  350  70.0   9
6   1반  김영자  71  71  51  84  57  334  66.8  11
7   2반  다니엘  87  54  95  71  97  404  80.8   3
8   3반  이미로  59  54  75  90  82  360  72.0   7
9   1반  신성삼  64  66  59  91  86  366  73.2   6
10  2반  케로로  56  76  52  64  65  313  62.6  12
11  3반  장발장  85  51  64  80  68  348  69.6  10

In [21]:
score["순위2"] = score["mean"].rank(method="dense", ascending = False).astype(int)
score

# method="max"   :  3위가 2개일때, 4위로 표시하고, 다음 순위는 5위로 
# method="min"   :  3위가 2개일때, 3위로 표시하고, 다음 순위는 5위로 
# method="dense" :  3위가 2개일때, 3위로 표시하고, 다음 순위는 4위로

     반   성명  국어  영어  수학  사회  과학  sum  mean  순위  순위2
0   1반  홍길동  93  80  94  73  64  404  80.8   3    3
1   2반  백일홍  93  63  76  84  92  408  81.6   2    2
2   3반  이삼상  94  74  86  90  70  414  82.8   1    1
3   1반  정말로  83  55  64  90  65  357  71.4   8    7
4   2반  한번도  87  95  66  75  60  383  76.6   5    4
5   3반  이철수  53  81  59  88  69  350  70.0   9    8
6   1반  김영자  71  71  51  84  57  334  66.8  11   10
7   2반  다니엘  87  54  95  71  97  404  80.8   3    3
8   3반  이미로  59  54  75  90  82  360  72.0   7    6
9   1반  신성삼  64  66  59  91  86  366  73.2   6    5
10  2반  케로로  56  76  52  64  65  313  62.6  12   11
11  3반  장발장  85  51  64  80  68  348  69.6  10    9

In [23]:
score.head()

    반   성명  국어  영어  수학  사회  과학  sum  mean  순위  순위2
0  1반  홍길동  93  80  94  73  64  404  80.8   3    3
1  2반  백일홍  93  63  76  84  92  408  81.6   2    2
2  3반  이삼상  94  74  86  90  70  414  82.8   1    1
3  1반  정말로  83  55  64  90  65  357  71.4   8    7
4  2반  한번도  87  95  66  75  60  383  76.6   5    4

In [24]:
# 새로운 시트로 엑셀파일에 추가
with pd.ExcelWriter("../../data/성적 처리.xlsx", engine='openpyxl', mode='a') as writer:
    score.to_excel(writer, sheet_name="수학통계함수", index=False)